export const GET_LIST_ADDRESS = "GET_LIST_ADDRESS";

export const GET_LIST_ADDRESS_SUCCESS = "GET_LIST_ADDRESS_SUCCESS";

export const GET_LIST_ADDRESS_FAILED = "GET_LIST_ADDRESS_FAILED";

export const RESET_LIST_ADDRESS = "RESET_LIST_ADDRESS";
